export const financeTypes = Object.freeze({
    FETCH_FINANCE: 'FETCH_FINANCE',
    FETCH_ERROR: 'FETCH_ERROR',
    SELECT_COMPANY: 'SELECT_COMPANY',
    STOP_FETCHING: 'STOP_FETCHING',
    RESET_COMPANY: 'RESET_COMPANY',
});
